config/routes.rb
Share::Application.routes.draw do
  root :to => 'home#index'

  match '/signin' => 'services#signin'
  match '/signout' => 'services#signout'
  match '/auth/:service/callback' => 'services#create' 
  match '/auth/failure' => 'services#failure'

  resources :services, :only => [:index, :create, :destroy] do
    collection do
      get 'signin'
      get 'signout'
      get 'signup'
      post 'newaccount'
      get 'failure'
    end
  end 

  get 'home/about'
  get 'home/terms_of_service'

  resources :apps, :only => [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :posts, :only => [:new, :create, :show, :edit, :update, :hide] do
      member do
        put :voteup
        put :votedown
      end

      resources :comments, :only => [:new, :create, :show, :edit, :update, :hide] do
        member do
          put :voteup
          put :votedown
        end
      end
    end
    collection do
      get 'popular'
      get 'recent'
    end
  end

  resources :users, :only => [:index, :show, :edit, :update] do
    collection do
      get "user_labels"
    end
    member do
      get 'votes'
      get 'posts'
    end
  end

  get 'posts' => 'posts#index'

  get 'search' => 'search#index'
  

end

app/models/user.rb
class User < ActiveRecord::Base
  # REQUIRES
  require "digest/md5"

  # INCLUDES
  include SavedBy

  # BEHAVIORS

  # ASSOCIATIONS
  has_many :services, :dependent => :destroy
  has_many :apps

  # CALLBACKS

  # SCOPES
  
  # CONSTANTS

  # ATTRIBUTES
  attr_accessible :nickname, :avatar, :last_ip, 
                  :website, :twitter, :linkedin, :facebook, :google_plus, 
                  :about

  # VALIDATIONS
  validates :name, :presence => true
  validates :nickname, :presence => true, :length => { :in => 1..32 }
  validates :about, :length => { :in => 0..2000 }
  validates :website, :length => { :in => 0..64 }
  validates :twitter, :length => { :in => 0..15 } # TODO increase for future?
  validates :linkedin, :length => { :in => 0..64 }
  validates :facebook, :length => { :in => 0..64 }
  validates :google_plus, :length => { :in => 0..64 }
  # validates_format_of :linkedin, :allow_blank => true, :with => /^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,6}(:[0-9]{1,5})?(\/.*)?$/ix
  # validates_format_of :facebook, :allow_blank => true, :with => /^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,6}(:[0-9]{1,5})?(\/.*)?$/ix
  # validates_format_of :google_plus, :allow_blank => true, :with => /^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,6}(:[0-9]{1,5})?(\/.*)?$/ix
  # validates_inclusion_of :is_notifiable, :in => [true, false]

  # CLASS METHODS
  def self.new_by_service_session_and_request(session, request)
    user = self.new
    user.name = session[:authhash][:name]
    user.nickname = user.name.slice(0,32) if !user.name.blank?
    user.email = session[:authhash][:email]
    user.last_ip = request.remote_ip
    user.services.build(:provider => session[:authhash][:provider], :uid => session[:authhash][:uid], :uname => session[:authhash][:name], :uemail => session[:authhash][:email])
    user
  end

  # INSTANCE METHODS
  def admin?
    nil
  end

  def picture(size=50)
    if avatar.nil?
      hash = Digest::MD5.hexdigest(self.email)
      "http://www.gravatar.com/avatar/#{hash}.jpg?s=#{size}"
    else
      avatar
    end
  end
  
  def picture_small(size=36)
    hash = Digest::MD5.hexdigest(self.email)
    "http://www.gravatar.com/avatar/#{hash}.jpg?s=#{size}"
  end

  def to_s
    self.nickname.blank? ? self.name : self.nickname
  end

  # PROTECTED METHODS
  protected

  # PRIVATE METHODS
  private

end

class Creator < User
  has_many :apps, :foreign_key => "created_by"
end

class Updater < User
  has_many :apps, :foreign_key => "updated_by"
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show, :user_labels]
  before_filter :find_user, :only => [:show, :edit, :update, :destroy]
  before_filter :find_services, :only => [:edit, :update]
  protect_from_forgery :except => [:index, :show]

  # GET
  # def index
  # end

  # GET
  # def show
  # end

  # GET
  # def edit
  # end

  # GET
  def user_labels
    @users = User.where(id: params[:user_ids].split(",").map(&:to_i).uniq).all
  end
  
  # PUT / POST
  def update
    # TODO permissions
    if @user.id == current_user.id
      @user.attributes = params[:user]
      # TODO Sanitize links
      # [:nickname, :email, :website, :twitter, :linkedin, :facebook, :google].each do |x|
      #   @user.attributes[x] = Sanitize.clean(@user.attributes[x])
      # end    
      if @user.save_update_by(current_user.id, request.remote_ip)
        flash[:notice] = "Successfully updated."
        redirect_to user_path(@user)
      else
        render "edit"
      end
    else
      flash[:error] = "You are not allowed to update this user."
      redirect_to user_path(@user)
    end
  end

  # DELETE
  # def destroy
  # end

  protected
  def find_user
    @user = User.find(params[:id])
  end

  def find_services
    @services = current_user.services.order("provider asc")
  end
end

app/views/users/edit.html.erb
<% content_for :page_title do -%>Editing Profile &amp; Preferences<% end -%>
<% content_for :content_header do -%>
<div class="page-header">
  <h1>Editing <%= "#{@user.nickname}'s" -%> Profile &amp; Preferences</h1>
</div>
<% end -%>

<div class="row">
  <div class="span8">
  <%= form_for @user, {:url => user_path(@user), :html=>{ :class => "form-horizontal" } } do |user_form| -%>
  <%= user_form.error_messages :header_tag => :h4, 
                   :header_message => "The following issues kept the profile from being saved:", 
                   :message => nil,
                   :class => "alert-message block-message error" -%>
    <fieldset>
      <legend>User Profile</legend>
      <div class="control-group">
        <%= label_tag(:user_nickname, "Nickname *", :class => "control-label") -%>
        <div class="controls">
          <%= user_form.text_field :nickname, {:maxlength => 32, :class => "span3"} -%>
          <p class="help-block">32 characters max length.</p>
        </div>
      </div>
      <div class="control-group">
        <%= label_tag(:user_nickname, "Picture", :class => "control-label") -%>
        <div class="controls">
          <%= image_tag(@user.picture(50)) -%>
          <p class="help-block">Change your picture at <a href="http://www.gravatar.com/">gravatar.com</a>.</p>
        </div>
      </div>
      <div class="control-group">
      <%= label_tag(:user_website, "Web Site", :class => "control-label") -%>
        <div class="controls">
          <div class="input-prepend">
            <span class="add-on">http://</span>
            <%= user_form.text_field :website, {:maxlength => 64, :class => "span3", :placeholder=>"domain/page"} -%>
          </div>
        </div>
      </div>
      <div class="control-group">
        <%= label_tag(:user_twitter, "Twitter", :class => "control-label") -%>
        <div class="controls">
          <div class="input-prepend">
            <span class="add-on">@</span>
            <%= user_form.text_field :twitter, {:maxlength => 15, :class => "span2", :placeholder=>"accountname"} -%>
          </div>
        </div> 
      </div>
      <div class="control-group">
        <%= label_tag(:user_linkedin, "LinkedIn", :class => "control-label") -%>
        <div class="controls">
          <div class="input-prepend">
            <span class="add-on">http://linkedin.com/pub/</span>
            <%= user_form.text_field :linkedin, {:maxlength => 50, :class => "span3", :placeholder=>"page"} -%>
          </div>
        </div>
      </div>
      <div class="control-group">
        <%= label_tag(:user_facebook, "Facebook", :class => "control-label") -%>
        <div class="controls">
          <div class="input-prepend">
            <span class="add-on">http://facebook.com/</span>
            <%= user_form.text_field :facebook, {:maxlength => 50, :class => "span3", :placeholder=>"page"} -%>
          </div>
        </div>
      </div>
      <div class="control-group">
        <%= label_tag(:user_google_plus, "Google+", :class => "control-label") -%>
        <div class="controls">
          <div class="input-prepend">
            <span class="add-on">https://plus.google.com/</span>
            <%= user_form.text_field :google_plus, {:maxlength => 50, :class => "span3", :placeholder=>"uniqueid/posts"} -%>
          </div>
        </div>
      </div>
      <div class="control-group">
        <%= label_tag(:user_about, "About", :class => "control-label") -%>
        <div class="controls">
          <%= user_form.text_area :about, {:size => "80x12", :class => "span6 markitup"} -%>
          <p class="help-block">
            Feel free to describe your interests and expertise. 2000 characters max length.
          </p>
        </div>
      </div>    
    </fieldset>
       
    <fieldset class="add-top">
      <legend>Preferences</legend>
      <div class="control-group">
        <label for="input">Notifications</label>
        <div class="controls">
          TODO
        </div>
      </div>          
    </fieldset>
    <div class="form-actions">
      <input type="submit" class="btn btn-primary half-left" value="Save">
    </div>
    </fieldset>
  <% end -%>
  </div>

  <div class="span3 well panel pull-right">
    <h2>Login Services</h2>
    <p>You can use these accounts to login:</p>
  
    <% @services.each do |service| %>  
      <div class="add-bottom">  
        <div>
            <% if ['aol', 'facebook', 'github', 'google', 'openid', 'twitter', 'yahoo'].index(service.provider) %>
            <%= image_tag "#{service.provider}_64.png", :size => "64x64" %>
          <% else %>
            <%= image_tag "openid_64.png", :size => "64x64" %>
          <% end %>
        </div>
      
        <div>
        <% if service.uid.starts_with?('http') %>
          <%= service.uid.scan(/http[s]*:\/\/.*?\//)[0] %>
        <% else %>
          <%= service.provider.capitalize %>: <%= service.uid %>
        <% end %>
        <br />
        <%= service.uname if service.uname != '' %><br />
        <%= service.uemail if service.uemail != '' %><br />
        <% if session[:service_id] == service.id %>
          <span class="btn disabled success small">Logged in</span>
        <% else %>
          <%= link_to "Remove this service", service, :confirm => 'Are you sure you want to remove this authentication?', :method => :delete, :class => "btn btn-small" %>
        <% end %>
        </div>
      </div>
    <% end %>

    <p>You can connect more accounts to login:<p>
    <%= render :partial => 'services/services_list' -%>
  </div>
</div>

app/views/users/show.html.erb
<% content_for :page_title do -%>Adding Your App<% end -%>
<% content_for :content_header do -%>
<div class="page-header">
  <% if user_signed_in? and (@user.id == current_user.id) -%>
  <div class="pull-right">
    <%= link_to "Edit Profile & Preferences &rarr;".html_safe, edit_user_path(@user), :class => "btn btn-large btn-primary" -%>
  </div>
  <% end -%>

  <h1><%= "#{@user.nickname}'s Profile" -%></h1>
</div>
<% end -%>

<div class="row">
  <div class="span4 well panel">
    <p><%= image_tag(@user.picture(50)) -%></p>
    <address>
      <strong>Apps</strong><br>
      <% @user.apps.each do |a| -%>
        <%= link_to a.name, app_path(a) -%><br>
      <% end -%>
      <br/>
      <strong>Web Site</strong><br>
      <%= link_to "http://#{@user.website}", "http://#{@user.website}" unless @user.website.blank? -%><br>
      <strong>Twitter</strong><br>
      <%= link_to "@#{@user.twitter}", "http://twitter.com/#{@user.twitter}" unless @user.twitter.blank? -%><br>
      <strong>LinkedIn</strong><br>
      <%= link_to "http://linkedin.com/pub/#{@user.linkedin}", "http://linkedin.com/pub/#{@user.linkedin}" unless @user.linkedin.blank? -%><br>
      <strong>Facebook</strong><br>
      <%= link_to "http://facebook.com/#{@user.facebook}", "http://facebook.com/#{@user.facebook}" unless @user.facebook.blank? -%><br>
      <strong>Google+</strong><br>
      <%= link_to "https://plus.google.com/#{@user.google_plus}", "http://plus.google.com/#{@user.google_plus}" unless @user.google_plus.blank? -%><br>
    </address>
  </div>

  <div class="span7">
    <%= markdown(@user.about) unless @user.about.blank? -%>
  </div>
</div>