config/routes.rb
Share::Application.routes.draw do
  root :to => 'home#index'

  match '/signin' => 'services#signin'
  match '/signout' => 'services#signout'
  match '/auth/:service/callback' => 'services#create' 
  match '/auth/failure' => 'services#failure'

  resources :services, :only => [:index, :create, :destroy] do
    collection do
      get 'signin'
      get 'signout'
      get 'signup'
      post 'newaccount'
      get 'failure'
    end
  end 

  get 'home/about'
  get 'home/terms_of_service'

  resources :apps, :only => [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :posts, :only => [:new, :create, :show, :edit, :update, :hide] do
      member do
        put :voteup
        put :votedown
      end

      resources :comments, :only => [:new, :create, :show, :edit, :update, :hide] do
        member do
          put :voteup
          put :votedown
        end
      end
    end
    collection do
      get 'popular'
      get 'recent'
    end
  end

  resources :users, :only => [:index, :show, :edit, :update] do
    collection do
      get "user_labels"
    end
    member do
      get 'votes'
      get 'posts'
    end
  end

  get 'posts' => 'posts#index'

  get 'search' => 'search#index'
  

end

app/views/apps/_card.html.erb
<li>
  <div class="thumbnail">
      <a href="<%= app_path(app) -%>">
        <% if app.images.size > 0 and !app.images.last.file.blank? -%>
          <%= image_tag(app.images.last.file.thumb.url, :alt => app.images.last.description) -%>
        <% else -%>
          <img src="http://placehold.it/260x210/3C424C/cccccc&text=<%= "#{CGI.escape app.name}" -%>" alt="">
        <% end -%>
        <div class="caption">
          <h3><%= app.name -%></h3>
          <div id="category-<%= app.id -%>" data-placeholder="category-score" data-category-key="<%= app.id -%>"># Posts</div>
        </div>
      </a>
  </div>
</li>

app/views/apps/_form.html.erb
<%= nested_form_for app, {:url => form_url, :html=>{ :multipart => true, :class => "form-horizontal" } } do |app_form| -%>
<%= app_form.error_messages :header_tag => :h4, 
                 :header_message => "The following issues kept the App from being added:", 
                 :message => nil,
                 :class => "alert-message block-message error" -%>
  <fieldset>
    <legend>App Information</legend>
    <div class="control-group">
      <%= label_tag(:app_name, "App Name *", :class => "control-label") -%>
      <div class="controls">
        <%= app_form.text_field :name, {:maxlength => 30, :class => "span3"} -%>
        <p class="help-block">Use your app's name or domain name. We suggest keeping it to 30 characters or less.</p>
      </div>
    </div>
    <div class="control-group">
    <%= label_tag(:app_website, "Web Site", :class => "control-label") -%>
      <div class="controls">
        <div class="input-prepend">
          <span class="add-on">http://</span>
          <%= app_form.text_field :website, {:maxlength => 64, :class => "span3", :placeholder=>"domain/page"} -%>
          <p class="help-block"><a href="#" class="btn btn-small">Get humans.txt</a> We can also grab your humans.txt file to prepopulate the app's About text.</p>
        </div>
      </div>
    </div>
    <div class="control-group">
      <%= label_tag(:app_about, "About *", :class => "control-label") -%>
      <div class="controls">
        <%= app_form.text_area :about, {:size => "80x12", :class => "span6 markitup"} -%>
        <p class="help-block">
          Describe what your app offers, what's in it, who built it, how your spreading the word about it, and why it's important. 4000 characters max length. Markdown is supported.
        </p>
      </div>
    </div>        
    <div class="control-group">
      <label id="optionsCheckboxes">User Platforms *</label>
      <div class="controls">
        <% @platforms.each do |p| -%>
          <label class="checkbox">
            <%= check_box_tag :platform_ids, p.id, @app.platforms.include?(p), :name => 'app[platform_ids][]' -%>
            <span><%= p.name -%></span>
          </label>
        </li>
        <% end -%>
        <p class="help-block">
          <strong>Note:</strong> Choose one or more.
        </p>
      </div>
    </div>      
  </fieldset>

  <fieldset class="add-top">
    <legend>Screenshots</legend>
    <%= app_form.fields_for :images do |image_fields| -%>
    <div class="control-group">
      <%= label_tag(:image_description, "Description", :class => "control-label") -%>
      <div class="controls">
        <%= image_fields.text_field :description, {:maxlength => 32, :class => "span3"} -%>
        <p class="help-block">32 characters or less.</p>
      </div>
    </div>
    <div class="control-group">
      <%= label_tag(:image_file, "File", :class => "control-label") -%>
      <div class="controls">
        <% if image_fields.object.file?-%>
          <%= "#{image_tag(image_fields.object.file.url, width: 105, height: 105, alt: image_fields.object.description )} &nbsp;".html_safe if image_fields.object.file? -%>
          <%= image_fields.hidden_field :file_cache %>
          <%= image_fields.link_to_remove(:class => "btn btn-small", :style=>"display:inline-block;") do -%>
            Remove this screenshot
          <% end -%>
        <% else -%>
          <%= image_fields.file_field :file -%>
          <%= image_fields.link_to_remove(:class => "btn btn-small", :style=>"display:inline-block;") do -%>
            Remove this screenshot
          <% end -%>
        <% end -%>
      </div>
    </div> 
    <% end -%>
    <div class="control-group">
    <%= app_form.link_to_add(:images, :style => "margin-left: 155px;", :class => "btn add-top") do -%>
      Add a screenshot
    <% end -%>
    </div>
  </fieldset>
     
  <fieldset class="add-top">
    <legend>Other Details</legend>
    <div class="control-group">
      <%= label_tag(:app_twitter, "Twitter", :class => "control-label") -%>
      <div class="controls">
        <div class="input-prepend">
          <span class="add-on">@</span>
          <%= app_form.text_field :twitter, {:maxlength => 15, :class => "span2", :placeholder=>"accountname"} -%>
        </div>
      </div> 
    </div>
    <div class="control-group">
      <%= label_tag(:app_facebook, "Facebook", :class => "control-label") -%>
      <div class="controls">
        <div class="input-prepend">
          <span class="add-on">http://facebook.com/</span>
          <%= app_form.text_field :facebook, {:maxlength => 50, :class => "span3", :placeholder=>"page"} -%>
        </div>
      </div>
    </div>
    <div class="control-group">
      <%= label_tag(:app_google_plus, "Google+", :class => "control-label") -%>
      <div class="controls">
        <div class="input-prepend">
          <span class="add-on">https://plus.google.com/</span>
          <%= app_form.text_field :google_plus, {:maxlength => 50, :class => "span3", :placeholder=>"uniqueid/posts"} -%>
        </div>
      </div>
    </div>
    <div class="control-group">
      <%= label_tag(:app_android, "Android Market", :class => "control-label") -%>
      <div class="controls">
        <div class="input-prepend">
          <span class="add-on">https://market.android.com/</span>
          <%= app_form.text_field :android, {:maxlength => 50, :class => "span3", :placeholder=>"page"} -%>
        </div>
      </div>
    </div>
    <div class="control-group">
      <%= label_tag(:app_itunes, "iTunes App Store", :class => "control-label") -%>
      <div class="controls">
        <div class="input-prepend">
          <span class="add-on">http://itunes.apple.com/</span>
          <%= app_form.text_field :itunes, {:maxlength => 50, :class => "span3", :placeholder=>"page"} -%>
        </div>
      </div>
    </div>        
  </fieldset>
  <div class="form-actions">
    <input type="submit" class="btn btn-primary half-left" value="Save">
  </div>
<% end -%>

app/views/apps/_mini_card.html.erb
<li>
  <div class="thumbnail">
      <a href="<%= app_path(app) -%>">
        <% if app.images.size > 0 and !app.images.last.file.blank? -%>
          <%= image_tag(app.images.last.file.thumb.url, :alt => app.images.last.description, :width=>"130", :height=>"55") -%>
        <% else -%>
          <img src="http://placehold.it/130x105/3C424C/cccccc&text=<%= "#{CGI.escape app.name}" -%>" alt="">
        <% end -%>
          <h6><%= app.name -%></h6>
      </a>
  </div>
</li>

app/views/apps/edit.html.erb
<% content_for :page_title do -%>Editing Your App<% end -%>
<% content_for :content_header do -%>
<div class="page-header">
  <div id="form-status" class="alert alert-info pull-right" style="display: none;"></div>
  <h1>Editing Your App</h1>
</div>
<% end -%>

<div class="row">
  <div class="span3 well panel yellow">
    <h2>What's Behind It?</h2>
    <p>People come to this site to know more about what makes your app tick.</p>
    <p>We recommend describing the following in the <strong>About</strong> field:</p>
    <dl>
      <dt>What your app offers</dt>
      <dd>Features, functions, data, processes, you name it!</dd>
      <dt>What's in it</dt>
      <dd>What are the different types of technology being used, such as languages, frameworks, and libraries. </dd>
      <dt>Who built it</dt>
      <dd>Tell us about the folks who are designing, developing, launching, and supporting the app.</dd>
      <dt>How you're spreading the word</dt>
      <dd>What are you doing to make sure that the right people know about your app?</dd>
      <dt>Why it's important</dt>
      <dd>Saving the best for last...</dd>                  
    </dl>
    <p>Also, upload a few <strong>Screenshots</strong>!</p>
  </div>

  <div class="span8">
    <%= render :partial => "form", :locals => { :app => @app, 
          :form_url => app_path(@app) } %>
  </div>
</div>

app/views/apps/index.html.erb
<% content_for :page_title do -%>Browse Apps<% end -%>
<% content_for :content_header do -%>
<div class="page-header">
  <div class="pull-right">
    <a href="/apps/new" class="btn btn-large btn-success">Add Your App &rarr;</a>
  </div>

  <h1>Browse Apps <%= "<small>page #{@apps.current_page} of #{@apps.num_pages} &bull; #{pluralize(@apps.total_count, 'app')}</small>".html_safe if @apps.num_pages > 0 -%></h1>
</div>
<% end -%>

<ul class="nav nav-pills">
  <li<%= " class=""active""" if params[:platform].blank? -%>><a href="/apps">All</a></li>
  <li<%= " class=""active""" if params[:platform] == "1" -%>><a href="/apps?platform=1">Web</a></li>
  <li<%= " class=""active""" if params[:platform] == "2" -%>><a href="/apps?platform=2">Android</a></li>
  <li<%= " class=""active""" if params[:platform] == "3" -%>><a href="/apps?platform=3">iOS</a></li>
  <li<%= " class=""active""" if params[:platform] == "4" -%>><a href="/apps?platform=4">Windows Phone</a></li>
</ul>

<ul class="thumbnails">
  <% @apps.each do |app| -%>
    <%= render :partial => 'card', 
               :locals => { :app => app } -%>
  <% end -%>
<!--  <li>
    <a href="#">
      <img class="thumbnail" src="http://placehold.it/210x210" alt="">
      <h3>anotherapp</h3>
      10 Posts &bull; 
      <span class="nowrap"><%= image_tag("http://placehold.it/10x10", :class=>"inline") -%> Tess</span>
    </a>
  </li> -->
</ul>
<% if @apps.num_pages > 1 -%>
  <%= paginate @apps -%>
<% end -%>

app/views/apps/new.html.erb
<% content_for :page_title do -%>Adding Your App<% end -%>
<% content_for :content_header do -%>
<div class="page-header">
  <div id="form-status" class="alert alert-info pull-right" style="display: none;"></div>
  <h1>Adding Your App</h1>
</div>
<% end -%>

<div class="row">
  <div class="span3 well panel yellow">
    <h2>What's Behind It?</h2>
    <p>People come to this site to know more about what makes your app tick.</p>
    <p>We recommend describing the following in the <strong>About</strong> field:</p>
    <dl>
      <dt>What your app offers</dt>
      <dd>Features, functions, data, processes, you name it!</dd>
      <dt>What's in it</dt>
      <dd>What are the different types of technology being used, such as languages, frameworks, and libraries. </dd>
      <dt>Who built it</dt>
      <dd>Tell us about the folks who are designing, developing, launching, and supporting the app.</dd>
      <dt>How you're spreading the word</dt>
      <dd>What are you doing to make sure that the right people know about your app?</dd>
      <dt>Why it's important</dt>
      <dd>Saving the best for last...</dd>                  
    </dl>
    <p>Also, upload a few <strong>Screenshots</strong>!</p>
  </div>

  <div class="span8">
    <%= render :partial => "form", :locals => { :app => @app, 
            :form_url => apps_path } %>
  </div>
</div>

app/views/apps/popular.html.erb
<% content_for :page_title do -%>Popular Apps<% end -%>
<% content_for :content_header do -%>
<div class="page-header">
  <div class="pull-right">
    <a href="/apps/new" class="btn btn-large btn-success">Add Your App &rarr;</a>
  </div>

  <h1>Popular Apps  <%= "<small>page #{@apps.current_page} of #{@apps.num_pages} &bull; #{pluralize(@apps.total_count, 'app')}</small>".html_safe if @apps.num_pages > 0 -%></h1>
</div>
<% end -%>

<ul class="nav nav-pills">
  <li<%= " class=""active""" if params[:platform].blank? -%>><a href="/apps/popular">All</a></li>
  <li<%= " class=""active""" if params[:platform] == "1" -%>><a href="/apps/popular?platform=1">Web</a></li>
  <li<%= " class=""active""" if params[:platform] == "2" -%>><a href="/apps/popular?platform=2">Android</a></li>
  <li<%= " class=""active""" if params[:platform] == "3" -%>><a href="/apps/popular?platform=3">iOS</a></li>
  <li<%= " class=""active""" if params[:platform] == "4" -%>><a href="/apps/popular?platform=4">Windows Phone</a></li>
</ul>

<ul class="thumbnails">
  <% @apps.each do |app| -%>
    <%= render :partial => 'card', 
               :locals => { :app => app } -%>
  <% end -%>
<!--  <li>
    <a href="#">
      <img class="thumbnail" src="http://placehold.it/210x210" alt="">
      <h3>anotherapp</h3>
      10 Posts &bull; 
      <span class="nowrap"><%= image_tag("http://placehold.it/10x10", :class=>"inline") -%> Tess</span>
    </a>
  </li> -->
</ul>
<% if @apps.num_pages > 1 -%>
  <%= paginate @apps -%>
<% end -%>

app/views/apps/recent.html.erb
<% content_for :page_title do -%>Recent Apps<% end -%>
<% content_for :content_header do -%>
<div class="page-header">
  <div class="pull-right">
    <a href="/apps/new" class="btn btn-large btn-success">Add Your App &rarr;</a>
  </div>

  <h1>Recent Apps <%= "<small>page #{@apps.current_page} of #{@apps.num_pages} &bull; #{pluralize(@apps.total_count, 'app')}</small>".html_safe if @apps.num_pages > 0 -%></h1>
</div>
<% end -%>

<ul class="nav nav-pills">
  <li<%= " class=""active""" if params[:days].blank? -%>><a href="/apps/recent">30 days</a></li>
  <li<%= " class=""active""" if params[:days] == "60" -%>><a href="/apps/recent?days=60">60 days</a></li>
  <li<%= " class=""active""" if params[:days] == "90" -%>><a href="/apps/recent?days=90">90 days</a></li>
</ul>

<ul class="thumbnails">
  <% @apps.each do |app| -%>
    <%= render :partial => 'card', 
               :locals => { :app => app } -%>
  <% end -%>
<!-- <li>
    <a href="#">
      <img class="thumbnail" src="http://placehold.it/210x210" alt="">
      <h3>iosapp</h3>
      19 Posts &bull; 
      <span class="nowrap"><%= image_tag("http://placehold.it/10x10", :class=>"inline") -%> Tess</span>
    </a>
  </li> -->
</ul>
<% if @apps.num_pages > 1 -%>
  <%= paginate @apps -%>
<% end -%>

app/views/apps/show.html.erb
<% content_for :page_title do -%><%= @app.name%><% end -%>
<% content_for :content_header do -%>
<div id="information" data-app-id="<%= @app.id %>"></div>
<div class="page-header">
  <div class="pull-right">
    <%= link_to("Edit &rarr;".html_safe, edit_app_path(@app), :class => "btn btn-large btn-primary") if user_signed_in? and (@app.user.id == current_user.id) -%>
  </div>

  <h1><%= @app.name%>
    <small><%= @platforms.map(&:name).join(' &bull; ').html_safe%></small>
    <!-- <span class="label warning">unverified</span> -->
  </h1>
</div>
<% end -%>

<% content_for :include_js do %>
<%= render partial: 'shared/handlebars/app_post', :locals => { :ident => '_post', :app => @app }%>
<%= render partial: 'shared/handlebars/pagination', :locals => { :ident => '_pagination'}%>
<%= javascript_include_tag "pages/apps_show" %>
<% end -%>


<div class="row">
  <div class="span6">
    <h2>About</h2>
    <p><em>Updated <%= time_ago_in_words(@app.updated_at) %> ago by <%= link_to @app.updater, user_path(@app.updater) -%></em></p>
    <% if @app.images.size > 0 -%>
      <ul class="thumbnails">
        <% @app.images.each do |image| -%>
        <li>
          <div class="thumbnail">
            <a href="#">
              <img src="<%= image.file.thumb.url -%>" alt="<%= image.description -%>" width="130" height="105">
            </a>
          </div>
        </li>
        <% end -%>
      </ul>
    <% end -%>
    <p><%= markdown(@app.about) -%></p>

    <h3>Links</h3>
    <address>
  	<% if @app.website.presence -%>
      <strong>Web Site</strong><br>
  	  <a href="http://<%= @app.website -%>">http://<%= @app.website %></a><br>
    <% end -%>
  	<% if @app.twitter.presence -%>
      <strong>Twitter</strong><br>
      <a href="http://twitter.com/<%= @app.twitter -%>">@<%= @app.twitter%></a><br>
    <% end -%>
    <% if @app.facebook.presence -%>
      <strong>Facebook</strong><br>
      <a href="http://facebook.com/<%= @app.facebook -%>">http://facebook.com/<%= @app.facebook -%></a><br>
    <% end -%>
    <% if @app.google_plus.presence -%>
      <strong>Google+</strong><br>
      <a href="http://plus.google.com/<%= @app.google_plus -%>">http://plus.google.com/<%= @app.facebook -%></a><br>
    <% end -%>
    <% if @app.itunes.presence -%>
      <strong>iTunes App Store</strong><br>
      <a href="http://itunes.apple.com/<%= @app.itunes -%>">http://itunes.apple.com/<%= @app.itunes -%></a>
    <% end -%>
    <% if @app.android.presence -%>
      <strong>Android Market</strong><br>
      <a href="https://market.android.com/<%= @app.android -%>">https://market.android.com/<%= @app.android -%></a>
    <% end -%>
    </address>
  </div>

  <div class="span6">
    <div class="pull-right">
    <% if user_signed_in? -%>
      <a href="#" data-controls-modal="modal-add-post" data-backdrop="static" class="btn btn-small btn-primary">Add Post</a>
    <% else -%>
      <a href="/signin" class="btn btn-small btn-success">Login to Post</a>
    <% end -%>
    </div>
    
    <h2>Posts <small id="pageInfo"></small></h2>
    <ul class="nav nav-pills">
      <li class="active"><a href="#">FIXME Popular</a></li>
      <li><a href="#">FIXME Recent</a></li>
      <li><a href="#">FIXME Topics</a></li>
      <li><a href="#">FIXME Links</a></li>
      <li><a href="#">FIXME Files</a></li>
    </ul>  
    <div id="sources">
  	Loading...
    </div>

    <div id="pagination" class="pagination">
    </div>
  </div>
</div>

<div id="modal-add-post" class="modal hide fade" style="display: none; ">
  <div class="modal-header">
    <a href="#" data-dismiss="modal" class="close">×</a>
    <h3>Add Post</h3>
  </div>
  <div class="modal-body">
	<%= form_tag app_posts_path(@app.id, :format => :json), :method => :post, :id =>"newsource" do %>
      <fieldset>
      	<div id="errors-container" class="clearfix" style="visibility: hidden;">
        	<div id="errors" class="input">
          </div>     
        </div>
        <div class="control-group">
          <label for="" class="control-label">Title *</label>
          <div class="controls">
      			<%= text_field_tag "source[title]", nil, :id => "xlInput", :size => "30", :class => "span5", :placeholder => ""%>
          </div>
        </div>
        <div class="control-group">
          <label for="" class="control-label">Link</label>
          <div class="controls">
      			<%= text_field_tag "source[url]", nil, :id => "prependedInput", :size => "16", :class => "span5",:placeholder =>""%>
          </div>
        </div>        
        <div class="control-group">
          <label for="" class="control-label">File</label>
          <div class="controls">
            <input class="input-file" id="fileInput" name="fileInput" type="file">
          </div>
        </div>        
        <div class="control-group">
          <label for="textarea" class="control-label">Text</label>
          <div class="controls">
      			<%= text_area_tag "source[text]", nil, :id => "textarea2", :rows => "5", :class => "span5"%>
          </div>
        </div>        
      </fieldset>
    <% end -%>
  </div>
  <div class="modal-footer">
    <a href="#" id="newsource-save" class="btn btn-primary">Save</a>
  </div>
</div>