config/routes.rb
Share::Application.routes.draw do
  root :to => 'home#index'

  match '/signin' => 'services#signin'
  match '/signout' => 'services#signout'
  match '/auth/:service/callback' => 'services#create' 
  match '/auth/failure' => 'services#failure'

  resources :services, :only => [:index, :create, :destroy] do
    collection do
      get 'signin'
      get 'signout'
      get 'signup'
      post 'newaccount'
      get 'failure'
    end
  end 

  get 'home/about'
  get 'home/terms_of_service'

  resources :apps, :only => [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :posts, :only => [:new, :create, :show, :edit, :update, :hide] do
      member do
        put :voteup
        put :votedown
      end

      resources :comments, :only => [:new, :create, :show, :edit, :update, :hide] do
        member do
          put :voteup
          put :votedown
        end
      end
    end
    collection do
      get 'popular'
      get 'recent'
    end
  end

  resources :users, :only => [:index, :show, :edit, :update] do
    collection do
      get "user_labels"
    end
    member do
      get 'votes'
      get 'posts'
    end
  end

  get 'posts' => 'posts#index'

  get 'search' => 'search#index'
  

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  before_filter :set_requested_url, :only => [:show]
  before_filter :find_app, :except => [:index] #, :only => [:new, :create, :show, :edit, :update, :destroy]
  # protect_from_forgery :except => [:show]

  # GET
  # def index
  # end
  
  # GET
  def show
    @post_id = params[:id] #this is actually the source key
  end
  
  # POST
  def create
    #[Share.config.endpoint, 'sources.json'].join('/') + "?api_key=" + Share.config.api_key
    response = RestClient.post(([Share.config.endpoint, 'sources.json'].join('/') + "?api_key=" + Share.config.api_key), {
      :source => params[:source], :category_ids => @app.id, :user_key => current_user.id, :user_role => "moderator"
    })
    
    render :text => response.body
  end
  
  # PUT / POST
  def update
    response = RestClient.post(([Share.config.endpoint,  'sources', params[:id] + '.json'].join('/') + "?api_key=" + Share.config.api_key), {
      :source => params[:source], :category_ids => @app.id, :user_key => current_user.id, :_method => :put,
      :user_role => "moderator"
    })
    
    render :text => response.body
  end

  # POST
  def voteup
    response = RestClient.post(([Share.config.endpoint, 'sources', params[:id] ,'up.json'].join('/') + "?api_key=" + Share.config.api_key), {
      :source_id => params[:post_id], 
      :category_keys => params[:app_id],
      :user_key => current_user.id
    })
    #Rails.logger.debug(response.inspect)
    render :text => response.body
  end

  # POST
  def votedown
    response = RestClient.post(([Share.config.endpoint, 'sources', params[:id],'down.json'].join('/') + "?api_key=" + Share.config.api_key), {
      :source_id => params[:post_id], 
      :category_keys => params[:app_id],
      :user_key => current_user.id
    })
    #Rails.logger.debug(response.inspect)
    render :text => response.body
  end

  protected
  def find_app
    @app ||= App.find(params[:app_id])
  end

  def set_requested_url
    if !user_signed_in?
      session[:requested_url] = app_post_url(params[:app_id], params[:id])
    end
  end
end

app/views/posts/index.html.erb
<% content_for :page_title do -%>Posts<% end -%>
<% content_for :content_header do -%>
<div class="page-header">
  <div class="pull-right">
    <a href="/apps/new" class="btn btn-large btn-success">Add Your App &rarr;</a>
  </div>

  <h1>Posts</h1>
</div>
<% end -%>

<div class="row">
  <div class="span5">
    <h2>Popular</h2>
    <div id="popular"></div>
  </div>
  <div class="span5 offset1 pull-right">
    <h2>Recent</h2>
    <div id="recent"></div>
  </div>
</div>


<!-- HANDLEBARS TEMPLATES -->
<%= render partial: 'shared/handlebars/post'%>
<!-- END HANDLEBARS TEMPLATES-->

<% content_for :include_js do %>
<script type="text/javascript">
$(document).ready(function() {
  Signalike.Source.top({
    success: function (sources) {
      //get the handlebar template
      var source   = $("#_post").html();
      var template = Handlebars.compile(source);
      //sources.items is the list of sources
      //sources.total is the number of sources in the list
      var compiled = [];
      var limit = 20;
      var i;
      var data = [];
      var user_ids = [];
      limit = Math.min(limit,sources.items.length);
      for(var x = 0; x < limit; x++) {
        i = sources.items[x];
        user_ids.push(i.user_id);
        data.push(i);
      }
      if (data.length > 0) {
        Users.getLabels(user_ids, function (user_data) {
          $.each(data, function (idx, i) {
            i.nickname = user_data[i["user_id"]]["nickname"];
            i.picture_small = user_data[i["user_id"]]["picture_small"];
            compiled.push(template(i))
          });
          $('#popular').html(compiled.join(''));
        });
      }
    }
  });

  Signalike.Source.latest({
    success: function (sources) {
      //get the handlebar template
      var source   = $("#_post").html();
      var template = Handlebars.compile(source);
      //sources.items is the list of sources
      //sources.total is the number of sources in the list
      var compiled = [];
      var limit = 20;
      var i;
      var data = [];
      var user_ids = [];
      limit = Math.min(limit,sources.items.length);
      for(var x = 0; x < limit; x++) {
        i = sources.items[x];
        user_ids.push(i.user_id);
        data.push(i);
      }
      if (data.length > 0) {
        Users.getLabels(user_ids, function (user_data) {
          $.each(data, function (idx, i) {
            i.nickname = user_data[i["user_id"]]["nickname"];
            i.picture_small = user_data[i["user_id"]]["picture_small"];
            compiled.push(template(i))
          });
          $('#recent').html(compiled.join(''));
        });
      }
    }
  });  
});
</script>
<% end %>

app/views/posts/show.html.erb
<% content_for :page_title do -%>FIXME PUT THE POST TITLE HERE : <%= @app.name -%><% end -%>
<% content_for :content_header do -%>
<div id="information" data-post-id="<%= @post_id %>" data-app-id="<%= params[:app_id] %>"></div>
<div class="page-header">
  <% if user_signed_in? -%>
  <div class="pull-right add-left">
    <a class="btn btn-large votesourceup">+</a> 
    <a class="btn btn-large votesourcedown">&#8722;</a>
    <a data-controls-modal="modal-edit-post" data-backdrop="static" class="btn btn-large btn-primary">Edit &rarr;</a>
  </div>
  <% end -%>
  <div id="post-header">
    Loading...
  </div>
</div>
<% end -%>

<div class="row">
  <div class="span6"> 
    <p id="post-text">Loading...</p>
    <h3>Link</h3>
    <ul>
      <li id="post-link">Loading...</li>
    </ul>
    <h3>File</h3>
    <ul>
      <li><a href="">FIXME.txt</a></li>
    </ul>   
  </div>

  <div class="span6">
    <div class="pull-right">
    <% if user_signed_in? -%>
      <a href="#" data-controls-modal="modal-add-response" data-backdrop="static" class="btn btn-small btn-primary response">Add Response</a>
    <% else -%>
      <a href="/signin" class="btn btn-small btn-success">Login to Respond</a>
    <% end -%>
    </div>

    <h2 class="add-bottom">Responses <small>FIXME: 5 responses</small></h2> 
    <div id="comments-section">
  	Loading..
    </div>
  </div>
</div>

<div id="modal-add-response" class="modal hide fade" style="display: none; ">
  <div class="modal-header">
    <a href="#" class="close">×</a>
    <h3>Add Response</h3>
  </div>
  <div class="modal-body">
    <%= form_tag app_post_comments_path(@app.id, @post_id, :format => :json), :method => :post, :id =>"newcomment" do %>
      <fieldset>
  	    <div id="errors-container" class="clearfix" style="visibility: hidden;">
          <div id="errors" class="input">
          </div>          
        </div>
        <div class="control-group">
		  <input type="hidden" name="comment[parent_id]" id="comment_parent_id" />
		  <label for="title">Title</label>
			<div class="controls">
	            <input type="text" name="comment[title]" />
	        </div>
          <label for="textarea">Text</label>
          <div class="controls">
            <textarea class="span5" id="comment_text" name="comment[text]" rows="12"></textarea>
          </div>
        </div>
      </fieldset>
    <% end %>
  </div>
  <div class="modal-footer">
    <a id="newcomment-save" href="#" class="btn primary">Save</a>
  </div>
</div>

<div id="modal-edit-response" class="modal hide fade" style="display: none; ">
  <div class="modal-header">
    <a href="#" class="close">×</a>
    <h3>Edit Response</h3>
  </div>
  <div class="modal-body">
    <%= form_tag app_post_path(@app.id, @post_id), :method => :put, :id =>"editcomment" do %>
      <fieldset>
  	    <div id="errors-container" class="clearfix" style="visibility: hidden;">
          <div id="errors" class="input">
          </div>          
        </div>
        <div class="control-group">
          <label for="textarea">Text</label>
          <input type="hidden" name="comment[parent_id]" id="edit_comment_parent_id" />
          <div class="controls">
            <textarea class="span5" id="edit_comment_text" name="comment[text]" rows="12"></textarea>
          </div>
        </div>
      </fieldset>
    <% end %>
  </div>
  <div class="modal-footer">
    <a id="editcomment-save" href="#" class="btn primary">Save</a>
  </div>
</div>

<div id="modal-edit-post" class="modal hide fade" style="display: none; ">
  <div class="modal-header">
    <a href="#" data-dismiss="modal" class="close">×</a>
    <h3>Edit Post</h3>
  </div>
  <div class="modal-body">
	<%= form_tag app_post_path(@app.id, @post_id, :format => :json), :method => :put, :id =>"editsource" do %>
      <fieldset>
      	<div id="errors-container" class="clearfix" style="visibility: hidden;">
        	<div id="errors" class="input">
          </div>     
        </div>
        <div class="control-group">
          <label for="" class="control-label">Title *</label>
          <div class="controls">
      			<%= text_field_tag "source[title]", nil, :id => "xlInput", :size => "30", :class => "span5", :placeholder => ""%>
          </div>
        </div>
        <div class="control-group">
          <label for="" class="control-label">Link</label>
          <div class="controls">
      			<%= text_field_tag "source[url]", nil, :id => "prependedInput", :size => "16", :class => "span5",:placeholder =>""%>
          </div>
        </div>        
        <div class="control-group">
          <label for="" class="control-label">File</label>
          <div class="controls">
            <input class="input-file" id="fileInput" name="fileInput" type="file">
          </div>
        </div>        
        <div class="control-group">
          <label for="textarea" class="control-label">Text</label>
          <div class="controls">
      			<%= text_area_tag "source[text]", nil, :id => "textarea2", :rows => "5", :class => "span5"%>
          </div>
        </div>        
      </fieldset>
    <% end -%>
  </div>
  <div class="modal-footer">
    <a href="#" id="editsource-save" class="btn btn-primary">Save</a>
  </div>
</div>

<% content_for :include_js do %>
<%= render partial: 'shared/handlebars/post_header', :locals => { :ident => '_post_header' }%>
<%= render partial: 'shared/handlebars/node', :locals => { :ident => 'node' }%>

<%= javascript_include_tag "pages/posts_show"%>
<% end %>